services:
  postgres:
    network_mode: 'host'
    image: postgres:14
    container_name: ss_postgres_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ss_postgres_data:/var/lib/postgresql/data

  azurite:
    network_mode: 'host'
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: azurite_storage
    volumes:
      - azurite_data:/data

volumes:
  ss_postgres_data:
  azurite_data:
