name: Auto-merge Dependabot

on:
  merge_group:
  pull_request:
    paths:
      - ".github/workflows/*"
      - "**/package*.json"

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: |
          # Check if the PR creator is dependabot[bot] or dependabot-preview[bot]
          if [[ "${{ github.event.pull_request.user.login }}" != "dependabot[bot]" && "${{ github.event.pull_request.user.login }}" != "dependabot-preview[bot]" ]]; then
            echo "PR creator is not dependabot[bot] or dependabot-preview[bot]. Exiting early."
            exit 0
          fi

          NUMBER=${{ github.event.pull_request.number }}
          gh pr merge $NUMBER --auto
          gh pr review $NUMBER --approve
        env:
          GH_TOKEN: ${{ secrets.AUTOMATION_PAT }}
